### PR TITLE
fix: Scroll issue

### LINKED ISSUE #209: Infinite scroll not working in chrome when zoomed out

### PR DESCRIPTION
**Pull request by samuveth**
Fixes #209 

Changes proposed in this pull request:
- add more initial limit on bigger screens
- reduce offsetHight by 100 so that scroll works on chrome when zoomed (works up to 67% zoomed out)
- 
-

### CODE REVIEW

File: src/helpers/utils.ts [hunk 1]
```diff
@@ -175,9 +175,10 @@ export function filterProposals(space, proposal, tab) {
 
 export function infiniteScroll() {
   window.onscroll = () => {
+    console.log(window.screen.height);
```
Comment (bonustrack) [inline src/helpers/utils.ts:178]: Can you remove this?
```suggestion
    console.log(window.screen.height);
```

File: src/helpers/utils.ts [hunk 2]
```diff
@@ -175,9 +175,10 @@ export function filterProposals(space, proposal, tab) {
...
     const bottomOfWindow =
-      document.documentElement.scrollTop + window.innerHeight ===
-      document.documentElement.offsetHeight;
+      document.documentElement.scrollTop + window.innerHeight >=
+      document.documentElement.offsetHeight - 100;
```
Comment (bonustrack) [inline src/helpers/utils.ts:181]: This could be a parameter in the infiniteScroll function we can call it `distance` like on the infinity scroll module we were using with Vue2.

Comment (samuveth) [reply src/helpers/utils.ts:181]: When would we want to change this value?

Comment (bonustrack) [reply src/helpers/utils.ts:180]: Probably never, but ideally we want to create UI components and functions generic and flexible enough that we can create a lib and reuse them in others codebase.

**Review by bonustrack — APPROVED** [review]

File: src/helpers/utils.ts (hunk 2 above)
Comment (samuveth) [reply src/helpers/utils.ts:180]: Ok
